Repository testing-library/vue-testing-library, pull requests merged in 2019-08, with the labels that each got.

#75 Use and expose a local copy of fireEvent
  src/vue-testing-library.js
  tests/__tests__/components/Button.vue
  tests/__tests__/fire-event.js
Labels: breaking change

#88 Add within() test example
  tests/__tests__/within.js
Labels: chore

#87 Add Vue Testing Library types from DefinitelyTyped
  README.md
  package-lock.json
  package.json
Labels: enhancement

#80 automatically clean up aftereach with optout using VTL_SKIP_AUTO_CLEANUP
  cleanup-after-each.js
  src/__tests__/auto-cleanup-skip.js
  src/__tests__/auto-cleanup.js
  src/__tests__/debug.js
  src/__tests__/functional.js
  src/__tests__/simple-button.js
  src/__tests__/stopwatch.js
  src/__tests__/stubs.js
  src/__tests__/vue-router.js
  src/__tests__/vueI18n.js
  src/__tests__/vuex.js
  src/__tests__/within.js
  src/vue-testing-library.js
Labels: breaking change
